# Generated by Django 5.2.6 on 2025-09-07 17:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='company_logo',
            field=models.ImageField(upload_to='companylogo/'),
        ),
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(default=1, upload_to='item_images/'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField()),
                ('profile', models.ImageField(upload_to='profile/')),
                ('staff_level', models.IntegerField(choices=[(0, 'Manager'), (1, 'Staff')], default=1)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
